### ISSUE TITLE
Doesn't work when termguicolors option is set

### ISSUE THREAD

**Issue by grr** [hickop/vim-hickop-colors#3]
The following patch appears to work for the simplest case, but then if you disable termguicolors, it won't work. So you'd need to set both cterm and gui colors at the same time.

    $ git diff
    diff --git a/colors/hickop.vim b/colors/hickop.vim
    index bb427de..434d7c5 100644
    --- a/colors/hickop.vim
    +++ b/colors/hickop.vim
    @@ -14,7 +14,7 @@ endif
    let g:colors_name="hickop"

    "colors{{{
    -if has("gui_running")
    +if has('gui_running') || (has('termguicolors') && &termguicolors)
        let s:v=" gui"
        let s:bla="#262626"
        let s:whi="#c6c6c6"

**Comment by hickop** [comment]
Thanks for the report !
